In [108]:
import numpy as np
import cv2

In [26]:
img = np.random.randint(255, size=(50, 50))

In [27]:
x = np.random.randint(50, size=(10, 1))

In [28]:
angles  = [i for i in range(-180 , 180 , 45)]

In [29]:
angles

[-180, -135, -90, -45, 0, 45, 90, 135]

In [30]:
features  = np.zeros((len(x),128))

In [33]:
len(x)

10

In [32]:
features

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [101]:
for i in range (1,len(x)):
    m = img[i-1:i+2 , i-1:i+2]
    n = np.reshape(m, -1)
    l = np.pad(n, (16**2 - len(n),0), 'constant')
    print(len(l))
    print(16**2)
    patch = np.reshape(l , (16,-1))
    
    p = np.pad(m, ((int(np.floor((8 - m.shape[1])/2)),int(np.ceil((8 - m.shape[1])/2))),(int(np.floor((8 - m.shape[1])/2)),int(np.ceil((8 - m.shape[1])/2)))), 'constant')
    print(p)

256
256
[[  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0  95  70 133   0   0   0]
 [  0   0 100  59  95   0   0   0]
 [  0   0 156 181 107   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]]
256
256
[[  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0  59  95 113   0   0   0]
 [  0   0 181 107 114   0   0   0]
 [  0   0  83 169 176   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]]
256
256
[[  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0 107 114 230   0   0   0]
 [  0   0 169 176 139   0   0   0]
 [  0   0 218  13 245   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]]
256
256
[[  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0 176 139  82   0   0   0]
 [  0   0  13 245 11

In [39]:
img[: ,1]

array([ 70,  59, 181,  83, 201, 228, 157, 208,  31, 121, 103, 194, 197,
       180,  19, 253, 252,  59,  11, 232, 195, 187, 187, 123,   1, 170,
       175,  42, 157,  26, 125,   3,  54,  92,  51, 243, 166, 181, 167,
       161,  30,  29, 190,  62, 161, 123, 217,  70,  23,  11])

In [67]:
m.shape[0]

6

In [100]:
int(np.ceil((16-15) /2))

1

In [102]:
x = np.round(x)

In [103]:
x

array([[28],
       [11],
       [ 4],
       [16],
       [47],
       [48],
       [36],
       [47],
       [28],
       [ 4]])

In [104]:
#################33333###

In [106]:
p

array([[  0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0, 190,  42, 208,   0,   0,   0],
       [  0,   0,  81,  43,   9,   0,   0,   0],
       [  0,   0,  30, 233, 193,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0]])

In [137]:
img = cv2.imread('/home/mahmoud/Documents/Computer vision/mini -projects/Mini Project 2 - Local Feature Matching/data/NotreDame/NotreDame1.jpg', cv2.IMREAD_GRAYSCALE)
print(img)

[[255 255 255 ... 244 243 241]
 [255 255 255 ... 244 242 240]
 [255 255 255 ... 243 242 241]
 ...
 [105 107 108 ... 120 122 121]
 [105 105 106 ... 118 121 119]
 [104 104 104 ... 121 123 120]]


In [140]:
gx = cv2.Sobel(img, cv2.CV_64F, 1, 0)
gy = cv2.Sobel(img, cv2.CV_64F, 0, 1)
mag, ang = cv2.cartToPolar(gx, gy)

In [141]:
mag

array([[ 0.        ,  0.        ,  0.        , ...,  4.        ,
        14.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  6.32455532,
        13.34166406,  2.        ],
       [ 0.        ,  0.        ,  0.        , ..., 10.29563014,
         6.        ,  6.        ],
       ...,
       [ 6.        , 12.80624847, 17.02938637, ..., 22.8035085 ,
        11.04536102,  8.        ],
       [ 8.        , 12.08304597, 18.86796226, ..., 17.72004515,
         2.82842712,  0.        ],
       [ 0.        ,  2.        ,  8.        , ..., 16.        ,
         0.        ,  0.        ]])

In [142]:
ang

array([[0.        , 0.        , 0.        , ..., 3.14159274, 3.14159274,
        0.        ],
       [0.        , 0.        , 0.        , ..., 3.46340823, 3.36840916,
        4.71238899],
       [0.        , 0.        , 0.        , ..., 4.20530748, 3.14159274,
        1.57079637],
       ...,
       [4.71238899, 5.60848475, 5.58087683, ..., 5.37335634, 4.80303478,
        4.71238899],
       [4.71238899, 5.139081  , 5.2708993 , ..., 0.28609979, 0.78523159,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [157]:
width = 4
for r in range(0,4):
    for c in range(0,4):
        
        cellMag = np.reshape(mag[r*width + 1 : r*width +width, c*width + 1:c*width +width] , -1);
#         cellDir = np.reshape(dir[r*width + 1:r*width +width, c*width + 1:c*width +width] , -1);
        
        

In [158]:
mag

array([[ 0.        ,  0.        ,  0.        , ...,  4.        ,
        14.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  6.32455532,
        13.34166406,  2.        ],
       [ 0.        ,  0.        ,  0.        , ..., 10.29563014,
         6.        ,  6.        ],
       ...,
       [ 6.        , 12.80624847, 17.02938637, ..., 22.8035085 ,
        11.04536102,  8.        ],
       [ 8.        , 12.08304597, 18.86796226, ..., 17.72004515,
         2.82842712,  0.        ],
       [ 0.        ,  2.        ,  8.        , ..., 16.        ,
         0.        ,  0.        ]])

In [159]:
inds = np.digitize(mag, angles)

In [161]:
inds.shape

(2048, 1536)

In [162]:
mag.shape


(2048, 1536)

In [163]:
inds

array([[5, 5, 5, ..., 5, 5, 5],
       [5, 5, 5, ..., 5, 5, 5],
       [5, 5, 5, ..., 5, 5, 5],
       ...,
       [5, 5, 5, ..., 5, 5, 5],
       [5, 5, 5, ..., 5, 5, 5],
       [5, 5, 5, ..., 5, 5, 5]])

AttributeError: 'list' object has no attribute 'shape'

In [166]:
norm = np.linalg.norm(inds)

In [167]:
norm

10156.667416037604

In [168]:
normal_array = inds/norm

In [169]:
normal_array

array([[0.00049229, 0.00049229, 0.00049229, ..., 0.00049229, 0.00049229,
        0.00049229],
       [0.00049229, 0.00049229, 0.00049229, ..., 0.00049229, 0.00049229,
        0.00049229],
       [0.00049229, 0.00049229, 0.00049229, ..., 0.00049229, 0.00049229,
        0.00049229],
       ...,
       [0.00049229, 0.00049229, 0.00049229, ..., 0.00049229, 0.00049229,
        0.00049229],
       [0.00049229, 0.00049229, 0.00049229, ..., 0.00049229, 0.00049229,
        0.00049229],
       [0.00049229, 0.00049229, 0.00049229, ..., 0.00049229, 0.00049229,
        0.00049229]])

In [180]:
 n = [normal_array > .2 ]

In [181]:
n

[array([[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]])]

In [173]:
descriptor = np.zeros((1, 4*4*8))


In [174]:
descriptor


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [176]:
j =0 
j = j+1


In [177]:
j++

SyntaxError: invalid syntax (<ipython-input-177-7daa8a46d915>, line 1)

In [ ]:
features1 = 

In [ ]:
num_feature = min(len(features1) , len)

In [22]:
import numpy as np
x = np.random.randint(0, 20, 10)
indx = np.argwhere(x > 10)

In [23]:
x1 = x[indx]

In [24]:
x

array([ 7,  0,  2, 13, 18, 10, 15, 10,  7,  1])

In [25]:
x1

array([[13],
       [18],
       [15]])

In [30]:
x= np.round(x)

In [31]:
x

array([ 7,  0,  2, 13, 18, 10, 15, 10,  7,  1])

In [32]:
    angles = [i for i in range(-180, 180, 45)]


In [33]:
angles


[-180, -135, -90, -45, 0, 45, 90, 135]

In [34]:
angles.shape

AttributeError: 'list' object has no attribute 'shape'

In [35]:
                orientations = np.zeros((8, 1))


In [39]:
orientations[8]


array([0.])